server:
  port: 8081

spring:
  application:
    name: ms-inventario
  datasource:
    # RNF-E01 y RF-I01: Aislamiento de BD (Database-per-Service) en PostgreSQL
    url: jdbc:postgresql://localhost:5432/smartlogix_inventory
    username: postgres
    password: postgres_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# RNF-O01: Configuración de Observabilidad con Actuator y Prometheus
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
