server:
  port: 8080

spring:
  application:
    name: bff-gateway
  # RF-B02: Seguridad OAuth2/JWT (Resource Server configurado para validar Tokens)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://dev-smartlogix.us.auth0.com/}
          secret-key: ${JWT_SECRET:}
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      # RF-B01: Enrutamiento Centralizado
      routes:
        - id: ms-inventario
          uri: ${MS_INVENTARIO_URI:http://localhost:8081}
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - name: JwtValidationFilter
        - id: ms-pedidos
          uri: ${MS_PEDIDOS_URI:http://localhost:8082}
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: JwtValidationFilter
        - id: ms-envios
          uri: ${MS_ENVIOS_URI:http://localhost:8083}
          predicates:
            - Path=/api/v1/shipping/**
          filters:
            - name: JwtValidationFilter
            # RF-B03: Circuit Breaker aplicado a la ruta de envíos
            - name: CircuitBreaker
              args:
                name: shippingCircuitBreaker
                fallbackUri: forward:/fallback/shipping

# Configuración del Circuit Breaker (Resilience4j)
resilience4j.circuitbreaker:
  instances:
    shippingCircuitBreaker:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 50s
      failureRateThreshold: 50

# RNF-O01: Observabilidad
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
